### DISCUSSION TITLE
[Detector Support]: Updated to 16.0 and did all the convertion from nvidia tensorrt to onnx and for some reason cuda is not working.

### DISCUSSION THREAD

**Discussion by Reapuh-UwU** [blakeblackshear/frigate#19551] [Detector Support] [answered]
### Describe the problem you are having

CUDA for some reason isn't being recognized anymore with ffmpeg and onnx and fail over using the CPU which takes up 100% usage cuz its using the cpu to decode and detect.

nvidia-smi works inside of the countainer
<img width="2557" height="1000" alt="Screenshot 2025-08-16 180906" src="https://github.com/user-attachments/assets/cd81da7e-4018-4f84-b45b-130fcc190960" />

### Version

0.16.0-c2f8de9

### Frigate config file

```yaml
mqtt:
  enabled: false
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
detectors:
  onnx:
    type: onnx
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
ffmpeg:
  hwaccel_args: preset-nvidia
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
model:
  model_type: yolo-generic
  path: /config/model_cache/onnx/yolox_x.onnx
  input_tensor: nchw
  input_dtype: float
  input_pixel_format: rgb
  width: 640
  height: 640
  labelmap_path: /labelmap/coco-80.txt
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
go2rtc:
  streams:
    porch:
      - rtsp://RTSP:[redacted]@192.168.2.193:554/h265Preview_01_main#audio=aac#video=h265#hardware
    living_room:
      - rtsp://RTSP:[redacted]@192.168.2.194:554/h265Preview_01_main#audio=aac#video=h265#hardware
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
cameras:
  front_porch: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/porch
          roles:
            - detect
            - record
    objects:
      track:
        - person
      filters:
        person:
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # # Optional: minimum score for the object to initiate tracking (default: shown below)
          # min_score: 0.6
          # # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          # threshold: 0.65
          mask:
            - 0.148,0.178,0.156,0.175,0.166,0.18,0.186,0.214,0.194,0.218,0.219,0.213,0.228,0.203,0.227,0.177,0.221,0.156,0.213,0.15,0.21,0.131,0.214,0.104,0.211,0.071,0.189,0.07,0.16,0.07,0.148,0.091,0.149,0.146
            - 0.564,0.124,0.541,0.339,0.647,0.378,0.668,0.14
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 13
      detections:
        retain:
          days: 13
    detect:
      enabled: true
    motion:
      mask:
        - 2965,1171,2287,620,2390,193,2405,161,2429,145,2430,112,2554,123,2723,149,2944,203,3216,269,3563,367,3840,487,3840,1430,3840,1739
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
  living_room: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          roles:
            - detect
            - record
    objects:
      track:
        - person
      filters:
        person:
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          # min_score: 0.6
          # # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          # threshold: 0.65
          mask:
            - 0.358,0.434,0.541,0.561,0.55,0.256,0.36,0.22
            - 0.234,0.188,0.292,0.162,0.291,0.107,0.237,0.116
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 13
      detections:
        retain:
          days: 13
    detect:
      enabled: true
    motion:
      mask:
        - 515,0,530,409,548,414,585,410,655,402,704,471,844,456,812,0
version: 0.16-0
detect:
  enabled: true
```

### docker-compose file or Docker CLI command

```yaml
docker run
  -d
  --name='frigate'
  --net='bridge'
  --pids-limit 2048
  --privileged=true
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Fuana"
  -e HOST_CONTAINERNAME="frigate"
  -e 'FRIGATE_RTSP_PASSWORD'='[redacted]'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-138a9a86-8d43-c169-4ce8-2b8e20776f8e'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='compute,utility,video'
  -e 'USE_FP16'='false'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8971]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png'
  -p '8971:8971/tcp'
  -p '8554:8554/tcp'
  -p '8555:8555/tcp'
  -p '8555:8555/udp'
  -v '/mnt/user/appdata/frigate_config/config/':'/config':'rw'
  -v '/mnt/user/Disk3/frigate_storage/':'/media/frigate':'rw'
  -v '/etc/localtime':'/etc/localtime':'rw'
  --runtime=nvidia
  --shm-size=1g
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000
  --restart unless-stopped 'ghcr.io/blakeblackshear/frigate:stable-tensorrt'
```

### Relevant Frigate log output

```shell
2025-08-16 18:18:33.403465264  [2025-08-16 18:18:33] frigate.app                    INFO    : Starting Frigate (0.16.0-c2f8de9)
2025-08-16 18:18:33.437181290  [2025-08-16 18:18:33] peewee_migrate.logs            INFO    : Starting migrations
2025-08-16 18:18:33.439504059  [2025-08-16 18:18:33] peewee_migrate.logs            INFO    : There is nothing to migrate
2025-08-16 18:18:33.511236794  [2025-08-16 18:18:33] frigate.app                    INFO    : Recording process started: 506
2025-08-16 18:18:33.513520408  [2025-08-16 18:18:33] frigate.app                    INFO    : Review process started: 519
2025-08-16 18:18:33.517776688  [2025-08-16 18:18:33] frigate.app                    INFO    : go2rtc process pid: 128
2025-08-16 18:18:33.544024571  [2025-08-16 18:18:33] detector.onnx                  INFO    : Starting detection process: 531
2025-08-16 18:18:33.562871791  [2025-08-16 18:18:33] frigate.detectors.plugins.onnx INFO    : ONNX: loaded onnxruntime module
2025-08-16 18:18:33.563855253  [2025-08-16 18:18:33] frigate.detectors.plugins.onnx INFO    : ONNX: loading /config/model_cache/onnx/yolox_x.onnx
2025-08-16 18:18:33.565960860  [2025-08-16 18:18:33] frigate.app                    INFO    : Output process started: 562
2025-08-16 18:18:33.750787152  2025/08/16 18:18:33 [error] 222#222: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", subrequest: "/auth", upstream: "http://127.0.0.1:5001/auth", host: "127.0.0.1:5000"
2025-08-16 18:18:33.750825695  2025/08/16 18:18:33 [error] 222#222: *10 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", host: "127.0.0.1:5000"
2025-08-16 18:18:33.872959491  [INFO] Starting go2rtc healthcheck service...
2025-08-16 18:18:34.503563027  2025-08-16 18:18:34.503488898 [E:onnxruntime:Default, cuda_call.cc:123 CudaCall] CUDA failure 999: unknown error ; GPU=-1 ; hostname=3c1ff0951ca7 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=67 ; expr=cudaGetDeviceCount(&num_devices); 
2025-08-16 18:18:34.683009331  [2025-08-16 18:18:34] frigate.app                    INFO    : Camera processor started for front_porch: 629
2025-08-16 18:18:34.707101312  [2025-08-16 18:18:34] frigate.app                    INFO    : Camera processor started for living_room: 631
2025-08-16 18:18:34.732308505  [2025-08-16 18:18:34] frigate.app                    INFO    : Capture process started for front_porch: 644
2025-08-16 18:18:34.771499228  [2025-08-16 18:18:34] frigate.app                    INFO    : Capture process started for living_room: 658
2025-08-16 18:18:34.923360315  [2025-08-16 18:18:34] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2025-08-16 18:18:35.252310844  [2025-08-16 18:18:35] frigate.api.fastapi_app        INFO    : FastAPI started
2025-08-16 18:18:36.257810072  [2025-08-16 18:18:36] frigate.video                  ERROR   : front_porch: Unable to read frames from ffmpeg process.
2025-08-16 18:18:36.258357689  [2025-08-16 18:18:36] frigate.video                  ERROR   : front_porch: ffmpeg process is not running. exiting capture thread...
2025-08-16 18:18:36.441913615  [2025-08-16 18:18:36] frigate.video                  ERROR   : living_room: Unable to read frames from ffmpeg process.
2025-08-16 18:18:36.442465090  [2025-08-16 18:18:36] frigate.video                  ERROR   : living_room: ffmpeg process is not running. exiting capture thread...
2025-08-16 18:18:36.581972414  [2025-08-16 18:18:36] frigate.detectors.plugins.onnx INFO    : ONNX: /config/model_cache/onnx/yolox_x.onnx loaded
2025-08-16 18:18:54.772947316  [2025-08-16 18:18:54] watchdog.front_porch           ERROR   : Ffmpeg process crashed unexpectedly for front_porch.
2025-08-16 18:18:54.773520622  [2025-08-16 18:18:54] watchdog.front_porch           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2025-08-16 18:18:54.774118384  [2025-08-16 18:18:54] ffmpeg.front_porch.detect      ERROR   : [AVHWDeviceContext @ 0x559ce8010b00] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
2025-08-16 18:18:54.774565671  [2025-08-16 18:18:54] ffmpeg.front_porch.detect      ERROR   : Device creation failed: -542398533.
2025-08-16 18:18:54.775010633  [2025-08-16 18:18:54] ffmpeg.front_porch.detect      ERROR   : [vist#0:0/hevc @ 0x559ce80015c0] [dec:hevc @ 0x559ce8034680] No device available for decoder: device type cuda needed for codec hevc.
2025-08-16 18:18:54.775449605  [2025-08-16 18:18:54] ffmpeg.front_porch.detect      ERROR   : [vist#0:0/hevc @ 0x559ce80015c0] [dec:hevc @ 0x559ce8034680] Hardware device setup failed for decoder: Generic error in an external library
2025-08-16 18:18:54.775869620  [2025-08-16 18:18:54] ffmpeg.front_porch.detect      ERROR   : [vost#1:0/rawvideo @ 0x559ce8006b00] Error initializing a simple filtergraph
2025-08-16 18:18:54.776279095  [2025-08-16 18:18:54] ffmpeg.front_porch.detect      ERROR   : Error opening output file pipe:.
2025-08-16 18:18:54.776674805  [2025-08-16 18:18:54] ffmpeg.front_porch.detect      ERROR   : Error opening output files: Generic error in an external library
2025-08-16 18:18:54.777019197  [2025-08-16 18:18:54] watchdog.front_porch           INFO    : Restarting ffmpeg...
2025-08-16 18:18:54.786430148  [2025-08-16 18:18:54] watchdog.living_room           ERROR   : Ffmpeg process crashed unexpectedly for living_room.
2025-08-16 18:18:54.786943089  [2025-08-16 18:18:54] watchdog.living_room           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2025-08-16 18:18:54.787335843  [2025-08-16 18:18:54] ffmpeg.living_room.detect      ERROR   : [AVHWDeviceContext @ 0x56467fd0e180] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
2025-08-16 18:18:54.787694542  [2025-08-16 18:18:54] ffmpeg.living_room.detect      ERROR   : Device creation failed: -542398533.
2025-08-16 18:18:54.788023916  [2025-08-16 18:18:54] ffmpeg.living_room.detect      ERROR   : [vist#0:0/hevc @ 0x56467fd25140] [dec:hevc @ 0x56467fd33480] No device available for decoder: device type cuda needed for codec hevc.
2025-08-16 18:18:54.788477865  [2025-08-16 18:18:54] ffmpeg.living_room.detect      ERROR   : [vist#0:0/hevc @ 0x56467fd25140] [dec:hevc @ 0x56467fd33480] Hardware device setup failed for decoder: Generic error in an external library
2025-08-16 18:18:54.789124129  [2025-08-16 18:18:54] ffmpeg.living_room.detect      ERROR   : [vost#1:0/rawvideo @ 0x56467fd09ac0] Error initializing a simple filtergraph
2025-08-16 18:18:54.789601734  [2025-08-16 18:18:54] ffmpeg.living_room.detect      ERROR   : Error opening output file pipe:.
2025-08-16 18:18:54.789879029  [2025-08-16 18:18:54] ffmpeg.living_room.detect      ERROR   : Error opening output files: Generic error in an external library
2025-08-16 18:18:54.790071984  [2025-08-16 18:18:54] watchdog.living_room           INFO    : Restarting ffmpeg...
```

### Install method

Docker CLI

### Object Detector

TensorRT

### Screenshots of the Frigate UI's System metrics pages

<img width="2544" height="1310" alt="image" src="https://github.com/user-attachments/assets/b5d5373c-e739-407d-967e-ed739bf2e911" />

### Any other information that may be helpful

Unraid 7.1.4
Nvidia driver: 575.64.03

docker screenshot of nvidia smi
<img width="755" height="456" alt="image" src="https://github.com/user-attachments/assets/3ea1c4bb-087b-4baa-ab9f-ed7f60e4b046" />

**Comment by inkeep-ai-assistant** [comment]
Based on your logs, the CUDA initialization is failing with "CUDA_ERROR_UNKNOWN: unknown error" for both FFmpeg and ONNX runtime. This is a common issue when there's a mismatch between the CUDA runtime version in the container and your host driver.

## Key Issues Identified

1. **ONNX Runtime Error**: The logs show `CUDA failure 999: unknown error ; GPU=-1` which indicates ONNX can't access the GPU [(1)](https://docs.frigate.video/configuration/object_detectors)
2. **FFmpeg Hardware Acceleration Failure**: FFmpeg is reporting `cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error` [(2)](https://docs.frigate.video/configuration/hardware_acceleration_video)

## Configuration Issues

Your configuration has some problems:

1. **Wrong Docker Image**: You're using `ghcr.io/blakeblackshear/frigate:stable-tensorrt` but have configured ONNX detector. For ONNX with NVIDIA GPU, you should use the `-tensorrt` image [(1)](https://docs.frigate.video/configuration/object_detectors)

2. **Missing Device Configuration**: Your ONNX detector configuration is missing the device specification [(3)](https://docs.frigate.video/configuration/object_detectors):

```yaml
detectors:
  onnx:
    type: onnx
    device: '0'  # Add this line
```
[(3)](https://docs.frigate.video/configuration/object_detectors)

3. **Model Configuration**: For YOLOx models, the configuration should be [(3)](https://docs.frigate.video/configuration/object_detectors):

```yaml
model:
  model_type: yolox
  width: 416  # should match the imgsize set during model export
  height: 416  # should match the imgsize set during model export
  input_tensor: nchw
  input_dtype: float_denorm  # Note: float_denorm, not float
  path: /config/model_cache/yolox_x.onnx
  labelmap_path: /labelmap/coco-80.txt
```
[(3)](https://docs.frigate.video/configuration/object_detectors)

## Recommended Solutions

1. **Use the correct Docker image**: Switch to `ghcr.io/blakeblackshear/frigate:stable-tensorrt` for NVIDIA GPU support with ONNX [(1)](https://docs.frigate.video/configuration/object_detectors)

2. **Add device specification** to your ONNX detector configuration [(3)](https://docs.frigate.video/configuration/object_detectors)

3. **Verify Docker GPU setup**: Ensure you have the NVIDIA Container Toolkit properly installed and configured [(2)](https://docs.frigate.video/configuration/hardware_acceleration_video)

4. **Check driver compatibility**: Your driver version 575.64.03 should be compatible, but verify it supports the CUDA version in the container [(2)](https://docs.frigate.video/configuration/hardware_acceleration_video)

The error pattern you're seeing is consistent with CUDA initialization failures, which typically occur when the container can't properly access the GPU hardware or there are driver/runtime mismatches.

📚 **Sources:**
1. [Supported Hardware](https://docs.frigate.video/configuration/object_detectors)
2. [Video Decoding](https://docs.frigate.video/configuration/hardware_acceleration_video)
3. [Supported Hardware](https://docs.frigate.video/configuration/object_detectors)

---

Have another question? Just tag [@inkeep](https://inkeep.com).

**Comment by NickM-27** [comment, marked as answer]
You are missing `--gpus=all`

**Reply by Reapuh-UwU** [reply]
after adding `--gpus=all` it seem to fix onnx but not ffmpeg.
<img width="1931" height="738" alt="image" src="https://github.com/user-attachments/assets/79c0e7ed-e225-4cd4-9ad5-0b3eb437bf56" />

**Reply by Reapuh-UwU** [reply]
I was about to fix it just by reinstalling the drivers but now the issue is detection is broken. in the debug section of the webui while standing on front of the camera it wouldn't detect me as a person. system usage whole spike up (my gpu and detector cpu usage)

**Reply by Reapuh-UwU** [reply]
I would just be just an interest but not labelling me as a person

**Reply by NickM-27** [reply]
I'm not sure why decoding wouldn't work, I have been using unraid with my Nvidia GPU throughout 0.16 and never had any issues. 

Are you sure you enabled detect? Detect is disabled by default in 0.16

**Reply by Reapuh-UwU** [reply]
in the config file above I added "detect: enabled: true" in both cameras and at the end so i assume its enabled and on the webui in a specific camera the detect is blue so its on.

**Reply by NickM-27** [reply]
What do the system metrics show, what is your current config

**Reply by Reapuh-UwU** [reply]
``` mqtt:
  enabled: false
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
detectors:
  onnx:
    type: onnx
    device: '0'
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
ffmpeg:
  hwaccel_args: preset-nvidia
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
model:
  model_type: yolo-generic
  path: /config/model_cache/onnx/yolox_tiny.onnx
  input_tensor: nchw
  input_dtype: float
  width: 416
  height: 416
  labelmap_path: /labelmap/coco-80.txt
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
go2rtc:
  streams:
    porch:
      - rtsp://RTSP:[redacted]@192.168.2.193:554/Preview_01_main#audio=aac#video=h264#hardware
    living_room:
      - rtsp://RTSP:[redacted]@192.168.2.194:554/Preview_01_main#audio=aac#video=h264#hardware
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
cameras:
  front_porch: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/porch
          roles:
            - detect
            - record
    objects:
      track:
        - person
      filters:
        person:
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # # Optional: minimum score for the object to initiate tracking (default: shown below)
          # min_score: 0.6
          # # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          # threshold: 0.65
          mask:
            - 0.148,0.178,0.156,0.175,0.166,0.18,0.186,0.214,0.194,0.218,0.219,0.213,0.228,0.203,0.227,0.177,0.221,0.156,0.213,0.15,0.21,0.131,0.214,0.104,0.211,0.071,0.189,0.07,0.16,0.07,0.148,0.091,0.149,0.146
            - 0.564,0.124,0.541,0.339,0.647,0.378,0.668,0.14
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 13
      detections:
        retain:
          days: 13
    detect:
      enabled: true
    motion:
      mask:
        - 2965,1171,2287,620,2390,193,2405,161,2429,145,2430,112,2554,123,2723,149,2944,203,3216,269,3563,367,3840,487,3840,1430,3840,1739
#~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o~~o
  living_room: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          roles:
            - detect
            - record
    objects:
      track:
        - person
      filters:
        person:
          # Optional: minimum width/height of the bounding box for the detected object (default: 0)
          min_ratio: 0.5
          # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
          max_ratio: 2.0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          # min_score: 0.6
          # # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          # threshold: 0.65
          mask:
            - 0.358,0.434,0.541,0.561,0.55,0.256,0.36,0.22
            - 0.234,0.188,0.292,0.162,0.291,0.107,0.237,0.116
    record:
      enabled: true
      retain:
        days: 0
        mode: all
      alerts:
        retain:
          days: 13
      detections:
        retain:
          days: 13
    detect:
      enabled: true
    motion:
      mask:
        - 515,0,530,409,548,414,585,410,655,402,704,471,844,456,812,0
version: 0.16-0
detect:
  enabled: true
```
  I changed the model to something smaller and hoped that it worked but it didnt.
<img width="2553" height="1311" alt="image" src="https://github.com/user-attachments/assets/abf83b47-b5c1-42df-811a-4a13864d4458" />

**Reply by NickM-27** [reply]
I see one problem, you're using yolo-generic with a YOLOx model which is incorrect

The input type is also incorrect for YOLOx

**Reply by hawkeye217** [reply]
Your `input_dtype` is incorrect for yolox. It should be `float_denorm`

See the docs: https://docs.frigate.video/configuration/object_detectors#yolox-1

**Reply by Reapuh-UwU** [reply]
It looks that these changes does the trick thank you! I missed the model_type changes. Also I am having weird issue way before updating to 16 where a person lets just say laying on the couch and is taking a nap and it wouldn't record them fully but in sections. 
<img width="116" height="105" alt="image" src="https://github.com/user-attachments/assets/3a248cde-f491-42a6-9aba-ab6a1a7422ea" />
this is me eating and I tried to in frame and the yellow is continuous but the red(which i assume whats being recorded) is cut

**Reply by NickM-27** [reply]
The red represents activity. If an object is stationary then it is not active

**Reply by Reapuh-UwU** [reply]
Oooh I see i see thank you. I was about to ask how to turn it off but reading the stationary_objects configuration you cant. Ig it is what it is. thank you for the help

**Reply by NickM-27** [reply]
You could make it a loitering zone

**Comment by DrSpaldo** [comment]
I am also (after a few times) going to give the nvidia detector a go to see how it performs vs coral tpu. In the docs/release notes you say this:

> _The TensorRT detector has been removed for Nvidia GPUs, the ONNX detector should be used instead._ 

However, then there is not an ONNX image. So that would make people assume you use ghcr.io/blakeblackshear/frigate:0.16.0 ... However, in this thread it says then you use ghcr.io/blakeblackshear/frigate:0.16.0-tensorrt

Is that right?

**Reply by NickM-27** [reply]
Yes, the tensorrt image is used as it has the tensorrt libraries included. That is generally unrelated to the detector

**Reply by DrSpaldo** [reply]
> Yes, the tensorrt image is used as it has the tensorrt libraries included. That is generally unrelated to the detector

But tensorrt is no longer being used? I'm confused

**Reply by NickM-27** [reply]
Tensorrt python library is no longer being used, ONNX runtime is used instead
