### DISCUSSION TITLE
[Detector Support]: Frigate 0.16 fails on Ryzen 5600G

### DISCUSSION THREAD

**Discussion by rea-ducks** [blakeblackshear/frigate#21464] [Detector Support]
### Describe the problem you are having

Today I tried to move from my Ryzen 5600G with iGPU running Frigate 0.15.2 with Yolo-NAS to 0.16.3 with Yolov9-s - and failed.
My running configuration always was quite slow (~60ms inference) and I read that Yolo-NAS doesn't work well with AMD iGPU anyways.
So I jumped to newest release, converted Yolov9-s to ONNX, adjusted my config and can't get it running. So I'm hoping for your expertise here.

With 0.15 I didn't need the "HSA_OVERRIDE_GFX_VERSION" at all, 0.16 didn't cope with gfx90c: "rocBLAS error: Cannot read /opt/rocm/lib/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx90c". So I added HSA_OVERRIDE_GFX_VERSION=9.0.0 which should work.

### Version

0.16.3

### Frigate config file

```yaml
detectors:
  onnx:
    type: onnx
model:
  model_type: yolo-generic
  width: 320
  height: 320
  input_tensor: nchw
  input_dtype: float
  path: /models/yolov9-s-320.onnx
  labelmap_path: /models/coco-80.txt
go2rtc:
  streams:
    eyethreeSD:
      - ffmpeg:rtsp://user:pw@192.168.8.62:554/channel=1&stream=1&protocol=unicast&onvif=0.sdp#video=h264#rotate=-90
  webrtc:
    candidates:
      - 192.168.8.151:8555
      - stun:8555
cameras:
  eyethree:
    live:
      streams:
        eyethreeSD: eyethreeSD
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/eyethreeSD
          roles:
            - detect
            - record
          input_args: preset-rtsp-restream
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      width: 448
      height: 800
      stationary:
        max_frames:
          objects:
            person: 100
birdseye:
  enabled: true
  mode: continuous
snapshots:
  enabled: true
  timestamp: false
  retain:
    default: 3
record:
  enabled: true
  retain:
    days: 1
    mode: active_objects
  alerts:
    retain:
      days: 2
    pre_capture: 15
    post_capture: 15
  detections:
    retain:
      days: 2
    pre_capture: 15
    post_capture: 15
database:
  path: /db/frigate.db
version: 0.16-0
detect:
  enabled: true
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: "ghcr.io/blakeblackshear/frigate:0.16.3-rocm"
    shm_size: '128mb'
    devices:
#      - /dev/dri/renderD129
      - /dev/dri
      - /dev/kfd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/:/config/
      - /opt/frigate/cctv:/media/frigate
      - /opt/frigate/db:/db
      - /opt/frigate/models:/models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8971:8971"
      - "1984:1984" # go2rtc
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC
      - "8555:8555/udp" # WebRTC
    environment:
      - PLUS_API_KEY=c07403c3-2eaf-45bb-8390-74f2ee2fe810:f2362fe5aa9666de1ebad2997e6220a8fb277e1c
      - TZ=Europe/Berlin
      - HSA_OVERRIDE_GFX_VERSION=9.0.0
```

### Relevant Frigate log output

```shell
frigate  | 2025-12-29 21:12:56.012596335  [2025-12-29 22:12:56] frigate.detectors.plugins.onnx INFO    : ONNX: /models/yolov9-s-320.onnx loaded
frigate  | 2025-12-29 21:12:56.012596335  [2025-12-29 22:12:56] frigate.detectors.plugins.onnx INFO    : ONNX: /models/yolov9-s-320.onnx loaded
frigate  | 2025-12-29 21:12:59.069356280  [INFO] Starting go2rtc healthcheck service...
frigate  | 2025-12-29 21:12:59.069356280  [INFO] Starting go2rtc healthcheck service...
frigate  | 2025-12-29 21:13:02.919899454  2025-12-29 22:13:02.919836694 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running QuickGelu node. Name:'node_silu/QuickGeluFusion/' Status Message: HIP error hipErrorInvalidDeviceFunction:invalid device function
frigate  | 2025-12-29 21:13:02.919899454  2025-12-29 22:13:02.919836694 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running QuickGelu node. Name:'node_silu/QuickGeluFusion/' Status Message: HIP error hipErrorInvalidDeviceFunction:invalid device function
frigate  | 2025-12-29 21:13:03.001442346  Process detector:onnx:
frigate  | 2025-12-29 21:13:03.001445076  Traceback (most recent call last):
frigate  | 2025-12-29 21:13:03.001446316    File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
frigate  | 2025-12-29 21:13:03.001447016      self.run()
frigate  | 2025-12-29 21:13:03.001447816    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
frigate  | 2025-12-29 21:13:03.001449566      return run(*args, **kwargs)
frigate  | 2025-12-29 21:13:03.001465076             ^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-12-29 21:13:03.001465976    File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
frigate  | 2025-12-29 21:13:03.001467196      self._target(*self._args, **self._kwargs)
frigate  | 2025-12-29 21:13:03.001468056    File "/opt/frigate/frigate/object_detection/base.py", line 136, in run_detector
frigate  | 2025-12-29 21:13:03.001468846      detections = object_detector.detect_raw(input_frame)


frigate  | 2025-12-29 21:13:03.001442346  Process detector:onnx:
frigate  | 2025-12-29 21:13:03.001445076  Traceback (most recent call last):
frigate  | 2025-12-29 21:13:03.001446316    File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
frigate  | 2025-12-29 21:13:03.001447016      self.run()
frigate  | 2025-12-29 21:13:03.001447816    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
frigate  | 2025-12-29 21:13:03.001449566      return run(*args, **kwargs)
frigate  | 2025-12-29 21:13:03.001465076             ^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-12-29 21:13:03.001465976    File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
frigate  | 2025-12-29 21:13:03.001467196      self._target(*self._args, **self._kwargs)
frigate  | 2025-12-29 21:13:03.001468056    File "/opt/frigate/frigate/object_detection/base.py", line 136, in run_detector
frigate  | 2025-12-29 21:13:03.001469546                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-12-29 21:13:03.001485707    File "/opt/frigate/frigate/object_detection/base.py", line 86, in detect_raw
frigate  | 2025-12-29 21:13:03.001486587      return self.detect_api.detect_raw(tensor_input=tensor_input)
frigate  | 2025-12-29 21:13:03.001487687             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-12-29 21:13:03.001488477    File "/opt/frigate/frigate/detectors/plugins/onnx.py", line 81, in detect_raw

frigate  | 2025-12-29 21:13:03.001485707    File "/opt/frigate/frigate/object_detection/base.py", line 86, in detect_raw
frigate  | 2025-12-29 21:13:03.001486587      return self.detect_api.detect_raw(tensor_input=tensor_input)
frigate  | 2025-12-29 21:13:03.001487687             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-12-29 21:13:03.001488477    File "/opt/frigate/frigate/detectors/plugins/onnx.py", line 81, in detect_raw
frigate  | 2025-12-29 21:13:03.001500717      tensor_output = self.model.run(None, {model_input_name: tensor_input})
frigate  | 2025-12-29 21:13:03.001501677                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-12-29 21:13:03.001502767    File "/usr/local/lib/python3.11/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 266, in run
frigate  | 2025-12-29 21:13:03.001503547      return self._sess.run(output_names, input_feed, run_options)
frigate  | 2025-12-29 21:13:03.001516707             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-12-29 21:13:03.001500717      tensor_output = self.model.run(None, {model_input_name: tensor_input})
frigate  | 2025-12-29 21:13:03.001501677                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-12-29 21:13:03.001502767    File "/usr/local/lib/python3.11/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 266, in run
frigate  | 2025-12-29 21:13:03.001503547      return self._sess.run(output_names, input_feed, run_options)
frigate  | 2025-12-29 21:13:03.001516707             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frigate  | 2025-12-29 21:13:03.001518397  onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running QuickGelu node. Name:'node_silu/QuickGeluFusion/' Status Message: HIP error hipErrorInvalidDeviceFunction:invalid device function
frigate  | 2025-12-29 21:13:12.494333440  [2025-12-29 22:13:12] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
frigate  | 2025-12-29 21:13:12.494333440  [2025-12-29 22:13:12] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
```

### Install method

Docker Compose

### Object Detector

Other

### Screenshots of the Frigate UI's System metrics pages

Frigates crashed to early to capture this.

**Comment by inkeep-ai-assistant** [comment]
The error `HIP error hipErrorInvalidDeviceFunction:invalid device function` you're encountering with your Ryzen 5600G (gfx90c) indicates a compatibility issue between ROCm, your integrated GPU, and the ONNX runtime in Frigate 0.16[(1)](https://docs.frigate.video/configuration/object_detectors)[(2)](https://github.com/blakeblackshear/frigate/discussions/19760).

The documentation notes that AMD ROCm support requires proper chipset version configuration. For ROCm to function, the software stack needs the correct `HSA_OVERRIDE_GFX_VERSION` setting[(1)](https://docs.frigate.video/configuration/object_detectors). Your gfx90c chipset is not automatically detected by Frigate's ROCm build, which currently only has automatic detection for gfx1031 (mapped to 10.3.0) and gfx1103 (mapped to 11.0.0)[(1)](https://docs.frigate.video/configuration/object_detectors).

While you've set `HSA_OVERRIDE_GFX_VERSION=9.0.0`, this may not be sufficient for your specific GPU architecture with the YOLOv9 model you're using[(1)](https://docs.frigate.video/configuration/object_detectors).

**Key points from the documentation:**

1. ROCm requires access to `/dev/kfd` and `/dev/dri` devices (which you have configured correctly)[(1)](https://docs.frigate.video/configuration/object_detectors)
2. AMD ROCm does not "officially" support integrated GPUs, though it can work with manual configuration[(1)](https://docs.frigate.video/configuration/object_detectors)
3. The `HSA_OVERRIDE_GFX_VERSION` environment variable must match your GPU's requirements[(1)](https://docs.frigate.video/configuration/object_detectors)
4. Some ONNX models may not be fully compatible with certain AMD integrated GPUs[(2)](https://github.com/blakeblackshear/frigate/discussions/19760)

**Recommended troubleshooting steps:**

First, verify ROCm is detecting your GPU by running this command in your container:
```bash
docker exec -it frigate /opt/rocm/bin/rocminfo
```
[(1)](https://docs.frigate.video/configuration/object_detectors)

This should list both CPU and GPU properties. If the GPU is not listed, ROCm is not initializing properly[(1)](https://docs.frigate.video/configuration/object_detectors).

To check your actual chipset version, run:
```bash
docker exec -it frigate /bin/bash -c '(unset HSA_OVERRIDE_GFX_VERSION && /opt/rocm/bin/rocminfo |grep gfx)'
```
[(1)](https://docs.frigate.video/configuration/object_detectors)

**Alternative approach:**

Given that YOLO-NAS models are known to not run well on integrated GPUs[(1)](https://docs.frigate.video/configuration/object_detectors), and you're experiencing issues with YOLOv9 on ROCm, you might consider using OpenVINO instead, which can run on AMD CPUs and may provide better compatibility:

```yaml
detectors:
  ov:
    type: openvino
    device: CPU

model:
  model_type: yolo-generic
  width: 320
  height: 320
  input_tensor: nchw
  input_dtype: float
  path: /config/model_cache/yolo.onnx
  labelmap_path: /labelmap/coco-80.txt
```
[(1)](https://docs.frigate.video/configuration/object_detectors)

You would need to use the default Frigate image (not `-rocm`) for OpenVINO support[(1)](https://docs.frigate.video/configuration/object_detectors).

The core issue is that your gfx90c integrated GPU may not have full ROCm support for the operations required by your YOLOv9 model, and without proper kernel module support or correct chipset override, GPU acceleration will fail[(1)](https://docs.frigate.video/configuration/object_detectors)[(2)](https://github.com/blakeblackshear/frigate/discussions/19760).

📚 **Sources:**
1. [Supported Hardware](https://docs.frigate.video/configuration/object_detectors)
2. [[Detector Support]:   HIP error hipErrorInvalidDeviceFunction:invalid device function, how to solve?](https://github.com/blakeblackshear/frigate/discussions/19760)

---

Have another question? Just tag [@inkeep](https://inkeep.com).

**Reply by NickM-27** [reply]
It is worth pointing out that integrated graphics have never been officially supported by AMD for ROCm or by Frigate

**Comment by rea-ducks** [comment]
I just went back to 0.15.2 and tried to switch from detector
  rocm:
    type: rocm
to
  onnx:
    type: onnx
with Yolo-NAS.

It works, and with inference of ~10ms - but not for long. Then it bails out with
```
frigate  | 2025-12-29 21:46:00.000965133  onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices
frigate  | 2025-12-29 21:46:00.000965613   index: 1 Got: 320 Expected: 3
frigate  | 2025-12-29 21:46:00.000966003   index: 3 Got: 3 Expected: 320
frigate  | 2025-12-29 21:46:00.000966453   Please fix either the inputs/outputs or the model.
```

Sidenote: rocm detector doesn't need HSA_OVERRIDE_GFX_VERSION=9.0.0 but onnx does, even on 0.15.

**Comment by vidgen13** [comment]
I tried what the bot suggested and it worked with openvino. Thanks AI

**Reply by rea-ducks** [reply]
Yes, it does. But it runs on CPU only then.
