### DISCUSSION TITLE
[Beta Support]: Face recognition crashes on startup with CUDA error on NVIDIA GPU

### DISCUSSION THREAD

**Discussion by daptify14** [blakeblackshear/frigate#22524] [Beta Support]
### Describe the problem you are having

Face recognition crashes on startup with CUDA error 901. The arcface model loads but fails on first inference. Everything else works fine — detection, embeddings, LPR, recordings, streaming. 

This worked on 0.17.0. The only thing that looks related and changed is the ORT/CUDA dependency bump in PR #22324. Also reproduced with no other GPU workloads and plenty of free VRAM, so does not seem to be an OOM issue.

Fixed by adding `arcface` to the `CudaGraphRunner.is_model_supported()` exclusion list in `detection_runners.py` — same pattern as the other excluded models. Face recognition then works on GPU through the regular ONNX runner.

```diff
 return model_type not in [
     ModelTypeEnum.yolonas.value,
     ModelTypeEnum.dfine.value,
     EnrichmentModelTypeEnum.paddleocr.value,
     EnrichmentModelTypeEnum.jina_v1.value,
     EnrichmentModelTypeEnum.jina_v2.value,
     EnrichmentModelTypeEnum.yolov9_license_plate.value,
+    EnrichmentModelTypeEnum.arcface.value,
 ]
```

Verified by bind-mounting the patched file. Before: crash at every startup. After: clean startup, face recognition working on GPU.

### Beta Version

0.18.0-e23a57d

### Issue Category

Object Detection / Detectors

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 10.10.0.35
  port: 1883

detectors:
  onnx:
    type: onnx

model:
  path: plus://51e953fa6345541e4082ef12ad235ccb

ffmpeg:
  hwaccel_args: preset-vaapi
  apple_compatibility: true
  output_args:
    record: preset-record-generic-audio-aac

detect:
  enabled: true
  fps: 5

face_recognition:
  enabled: true
  model_size: large

semantic_search:
  enabled: true
  model_size: large

lpr:
  enabled: true
  device: GPU
  model_size: small

objects:
  track:
    - person
    - face
    - car
    - motorcycle
    - bicycle
    - dog
    - cat
    - package
    - deer
    - raccoon

record:
  enabled: true
  continuous:
    days: 30
  alerts:
    retain:
      days: 60
      mode: all
  detections:
    retain:
      days: 45
      mode: all

snapshots:
  enabled: true
  clean_copy: false
  crop: true
  retain:
    default: 30

birdseye:
  enabled: true
  mode: continuous
  restream: true
  width: 1920
  height: 1080

audio:
  enabled: true
  min_volume: 300
  listen:
    - bark
    - fire_alarm
    - scream
    - glass_breaking
    - siren
    - car_alarm

logger:
  default: info
  logs:
    frigate.face_recognition: debug

genai:
  default:
    provider: openai
    api_key: not-needed
    model: qwen3.5-4b
    provider_options:
      context_size: 16384
    roles:
      - embeddings
      - vision
      - tools

go2rtc:
  streams:
    driveway:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.40.4:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:driveway#audio=opus
    driveway_sub:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.40.4:554/cam/realmonitor?channel=1&subtype=2
    front_door:
      - ffmpeg:http://192.168.40.7/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=onvif&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus
    front_door_sub:
      - ffmpeg:http://192.168.40.7/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=onvif&password={FRIGATE_RTSP_PASSWORD}
    back_door:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.40.5:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:back_door#audio=opus
    back_door_sub:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.40.5:554/cam/realmonitor?channel=1&subtype=2
    basement_door:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.40.6:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:basement_door#audio=opus
    basement_door_sub:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.40.6:554/cam/realmonitor?channel=1&subtype=2

cameras:
  driveway:
    birdseye:
      order: 1
    live:
      streams:
        Main: driveway
        Sub: driveway_sub
    lpr:
      enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    detect:
      annotation_offset: -2
    motion:
      mask:
        motion_mask_1:
          coordinates: 0.002,0,0,0.488,0.47,0.052,0.471,0
        motion_mask_2:
          coordinates: 0.826,0.075,0.839,0.394,0.812,1,1,1,1,0,0.822,0
      threshold: 50
      contour_area: 25
      improve_contrast: true
    objects:
      track:
        - person
        - face
        - car
        - motorcycle
        - bicycle
        - dog
        - cat
        - license_plate
        - package
        - deer
        - raccoon
    zones:
      driveway_approach:
        coordinates: 0.489,0.06,0.799,0.061,0.79,0.134,0.408,0.141
        inertia: 2
      driveway_garage:
        coordinates: 0.819,0.61,0.801,1,0.366,1,0.366,0.929,0.579,0.923,0.69,0.922,0.76,0.461,0.825,0.469
        inertia: 2
      driveway_main:
        coordinates: 0,0.60,0,0.538,0.403,0.149,0.793,0.144,0.793,0.453,0.757,0.449,0.685,0.912,0.361,0.921,0.361,1,0.01,1
        inertia: 2
    snapshots:
      required_zones:
        - driveway_approach
        - driveway_main
        - driveway_garage
    review:
      alerts:
        required_zones:
          - driveway_approach
          - driveway_main
          - driveway_garage
      genai:
        enabled: true
        alerts: true
        image_source: recordings
    audio:
      listen:
        - bark
        - fire_alarm
        - scream
        - glass_breaking
        - siren
        - car_alarm
  front_door:
    birdseye:
      order: 3
    live:
      streams:
        Main: front_door
        Sub: front_door_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
            - audio
    motion:
      threshold: 50
      contour_area: 50
      improve_contrast: true
    objects:
      track:
        - person
        - face
        - dog
        - cat
        - package
        - deer
        - raccoon
    review:
      genai:
        enabled: true
        alerts: true
        image_source: recordings
  back_door:
    birdseye:
      order: 2
    live:
      streams:
        Main: back_door
        Sub: back_door_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/back_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 50
      contour_area: 40
      improve_contrast: true
    objects:
      track:
        - person
        - dog
        - cat
        - deer
        - raccoon
  basement_door:
    birdseye:
      order: 4
    live:
      streams:
        Main: basement_door
        Sub: basement_door_sub
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/basement_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/basement_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      threshold: 50
      contour_area: 40
      improve_contrast: true
      mask:
        motion_mask_1:
          coordinates: 0.003,0.185,0.438,0.053,0.695,0.046,0.705,0.079,0.964,0.081,0.961,0,0.002,0.003
    objects:
      track:
        - person
        - dog
        - cat
        - deer
        - raccoon

telemetry:
  stats:
    intel_gpu_device: drm:/dev/dri/renderD129
```

### Relevant Frigate log output

```shell
2026-03-18 14:18:30.720999684  2026-03-18 14:18:30.720931386 [E:onnxruntime:, sequential_executor.cc:572 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/layer4/layer4.0/conv2/Conv' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:358 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*) Failed to allocate memory for requested buffer of size 9970176
2026-03-18 14:18:30.721003117
2026-03-18 14:18:30.722244780  loading data from : /config/model_cache/facedet/landmarkdet.yaml
2026-03-18 14:18:30.723442170  Exception in thread Thread-4 (build_model):
2026-03-18 14:18:30.723443912  Traceback (most recent call last):
2026-03-18 14:18:30.723445256    File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
2026-03-18 14:18:30.723446218      self.run()
2026-03-18 14:18:30.723447394    File "/usr/lib/python3.11/threading.py", line 975, in run
2026-03-18 14:18:30.723448527      self._target(*self._args, **self._kwargs)
2026-03-18 14:18:30.723449844    File "/opt/frigate/frigate/data_processing/common/face/model.py", line 303, in build_model
2026-03-18 14:18:30.723452289      emb = self.face_embedder([img])[0].squeeze()
2026-03-18 14:18:30.723453302            ^^^^^^^^^^^^^^^^^^^^^^^^^
2026-03-18 14:18:30.723467702    File "/opt/frigate/frigate/embeddings/onnx/base_embedding.py", line 94, in __call__
2026-03-18 14:18:30.723469001      outputs = self.runner.run(onnx_inputs)[0]
2026-03-18 14:18:30.723470032                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-03-18 14:18:30.723486242    File "/opt/frigate/frigate/detectors/detection_runners.py", line 246, in run
2026-03-18 14:18:30.723487501      self._session.run_with_iobinding(self._io_binding, ro)
2026-03-18 14:18:30.723498739    File "/usr/local/lib/python3.11/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 407, in run_with_iobinding
2026-03-18 14:18:30.723500030      self._sess.run_with_iobinding(iobinding._iobinding, run_options)
2026-03-18 14:18:30.723509975  RuntimeError: Error in execution: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:129 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; SUCCTYPE = cudaError; std::conditional_t<THRW, void, common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; SUCCTYPE = cudaError; std::conditional_t<THRW, void, common::Status> = void] CUDA failure 901: operation failed due to a previous error during capture ; GPU=0 ; hostname=8a7e7e31d1df ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_graph.cc ; line=61 ; expr=cudaStreamEndCapture(stream_, &graph);
```

### Install method

Proxmox via Docker

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:e23a57d-tensorrt
    restart: unless-stopped
    shm_size: 4gb
    devices:
      - nvidia.com/gpu=all
      - /dev/dri/renderD129:/dev/dri/renderD129
    volumes:
      - /opt/docker/app_data/frigate/config:/config
      - /media/frigate/recordings:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      #- ./detection_runners.py:/opt/frigate/frigate/detectors/detection_runners.py:ro  # arcface CUDA graph fix
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
      PLUS_API_KEY: ${PLUS_API_KEY}
```

### Operating system

Debian

### CPU / GPU / Hardware

Intel Core i5-8500, NVIDIA RTX 3050 6GB, host driver 580.126.09, Proxmox LXC with GPU passthrough.

**Comment by NickM-27** [comment]
I saw this too but it was fixed by setting the semantic search to small. Odds are there is some specific cuda error. Will likely continue to monitor as using cuda graphs is preferred.

**Comment by abcooke0** [comment]
I had raised a simular issue here: https://github.com/blakeblackshear/frigate/discussions/22575 before seeing this one.
I'm now using 0.18.0-b821420 and have had to set Semantic Search, Face Recognition and LPR to small as large no longer work.

**Comment by daptify14** [comment]
After the CUDA downgrade in PR #22589, I have no issues running Semantic Search, Face Recognition, and LPR all set to large on an RTX 5060 Ti. 
But 0.18.0-b821420 looks like it included that downgrade, so this may be a different issue on your end.

**Reply by NickM-27** [reply]
Thanks for confirming
