### DISCUSSION TITLE
[Development]: ONNX Runtime / CUDA Graph crash (CUDA failure 901) when initializing Face Recognition on dev build ec7040b

### DISCUSSION THREAD

**Discussion by abcooke0** [blakeblackshear/frigate#22575] [Beta Support]
### Describe the problem you are having

When running the latest 0.18 dev build (ec7040b), Frigate crashes during startup when attempting to allocate memory and build the model for Face Recognition.

The system initially throws a BFCArena memory allocation error for a Conv node, which immediately cascades into a CUDA failure 901 during cudaStreamEndCapture, bringing down the entire thread. This configuration was running perfectly stable on previous dev builds, suggesting a recent regression in how ONNX/CUDA graphs are allocating or managing GPU memory alongside other hardware-accelerated tasks (YOLO, Whisper).

### Beta Version

0.18.0-ec7040b

### Issue Category

Hardware Acceleration

### Frigate config file

```yaml
detectors:
  rtx3060:
    type: onnx
    device: GPU
model:
  model_type: yolo-generic
  width: 320 
  height: 320 
  input_tensor: nchw
  input_dtype: float
  path: /config/model_cache/yolov9-s-320.onnx
  labelmap_path: /labelmap/coco-80.txt

# HW Accel Auto-detected for 5x 1080p streams

face_recognition:
  enabled: true
  model_size: small 
  save_attempts: 2000

audio_transcription:
  enabled: true
  device: GPU
```

### Relevant Frigate log output

```shell
[E:onnxruntime:, sequential_executor.cc:572 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/layer4/layer4.0/conv2/Conv' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:358 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*) Failed to allocate memory for requested buffer of size 9970176
loading data from : /config/model_cache/facedet/landmarkdet.yaml
Exception in thread Thread-4 (build_model):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/data_processing/common/face/model.py", line 303, in build_model
    emb = self.face_embedder([img])[0].squeeze()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/frigate/frigate/embeddings/onnx/base_embedding.py", line 94, in __call__
    outputs = self.runner.run(onnx_inputs)[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/frigate/frigate/detectors/detection_runners.py", line 246, in run
    self._session.run_with_iobinding(self._io_binding, ro)
  File "/usr/local/lib/python3.11/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 407, in run_with_iobinding
    self._sess.run_with_iobinding(iobinding._iobinding, run_options)
RuntimeError: Error in execution: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:129 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; SUCCTYPE = cudaError; std::conditional_t<THRW, void, common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, SUCCTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; SUCCTYPE = cudaError; std::conditional_t<THRW, void, common::Status> = void] CUDA failure 901: operation failed due to a previous error during capture ; GPU=0 ; hostname=b4b4aab78692 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_graph.cc ; line=61 ; expr=cudaStreamEndCapture(stream_, &graph);
```

### Install method

Docker Compose

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:ec7040b-tensorrt
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    shm_size: 2048m # or '2g'
   # devices:
      # IF you have a second card/Dual-TPU, change to >
      # IF you only have one card, this works only if >
      #- /dev/apex_0:/dev/apex_0
    environment:
      - FRIGATE_RTSP_PASSWORD=password
    volumes:
      #- /SSD1TB/frigate/storage:/media/frigate
      - /mnt/1TBSSD/frigate/storage:/media/frigate
      - /frigate/config:/config
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000  # This is 1GB (1_000_000_000 bytes)
    ports:
      - "5002:5000"
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

### Operating system

Debian

### CPU / GPU / Hardware

NVIDIA RTX 3060 (12GB VRAM)

### Steps to reproduce

1. Run Frigate 0.18.0-ec7040b on an NVIDIA GPU (RTX 3060).
2. Enable multiple GPU-accelerated features (YOLOv9 via ONNX, Audio Transcription on GPU).
3. Enable face_recognition.
4. Start Frigate. The crash occurs immediately upon loading landmarkdet.yaml and building the face embedder.

**Comment by NickM-27** [comment]
it is an intermittent error, not something that happens every time. In my case the error went away when setting semantic search to small.

**Reply by abcooke0** [reply]
I am running the latest dev build (0.18.0-b821420) and ever since PR #22589 (downgrading to CUDA 12.8/12.9) was merged, Frigate crashes on startup during the face detection model load. I did not have this issue prior to this PR.

My GPU is a RTX3060 12gb

Here is the exact error trace showing the BFC allocator failing during the graph capture:
[E:onnxruntime:, sequential_executor.cc:572 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/layer4/layer4.0/conv2/Conv' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:358 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*) Failed to allocate memory for requested buffer of size 9970176
CUDA failure 901: operation failed due to a previous error during capture ; GPU=0 ; hostname=b4b4aab78692 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_graph.cc ; line=61 ; expr=cudaStreamEndCapture(stream_, &graph);

It seems the CUDA downgrade reintroduced the aggressive BFC allocation bug for my hardware architecture. Is there a way to expose a toggle for enable_cuda_graph in the config, or revert this for certain architectures?

**Reply by smartypantsuk** [reply]
Workaround found:
Traced this to CudaGraphRunner.is_model_supported() in frigate/detectors/detection_runners.py. Frigate already excludes several model types known to be incompatible with CUDA Graph capture (yolonas, dfine, paddleocr, jina_v1, jina_v2, yolov9_license_plate) — but the face recognition embedding types (arcface, facenet) aren't in that exclusion list, despite hitting the same underlying incompatibility.
Adding both to the exclusion list resolves the crash entirely.

Patch:

```
# frigate/detectors/detection_runners.py, inside CudaGraphRunner.is_model_supported()
return model_type not in [
    ModelTypeEnum.yolonas.value,
    ModelTypeEnum.dfine.value,
    EnrichmentModelTypeEnum.paddleocr.value,
    EnrichmentModelTypeEnum.jina_v1.value,
    EnrichmentModelTypeEnum.jina_v2.value,
    EnrichmentModelTypeEnum.yolov9_license_plate.value,
    EnrichmentModelTypeEnum.arcface.value,   # added
    EnrichmentModelTypeEnum.facenet.value,   # added
]
```
Tested over several hours with face recognition (large), semantic search (large), and LPR all enabled simultaneously — zero crashes since applying this, versus intermittent crashes on nearly every restart before. Would be great to see this upstreamed into the default exclusion list, since it seems like a straightforward oversight rather than a deliberate omission.

**Comment by ef1970** [comment]
Some more data on this one, since it's still open. I think the cause is pinned down.

`arcface` is the only ONNX Runtime enrichment model that isn't in `CudaGraphRunner.is_model_supported()`'s exclusion list — `paddleocr`, `yolov9_license_plate`, `jina_v1` and `jina_v2` are all already there. On my Blackwell card the graph capture fails about two thirds of the time, and when it does, face recognition stops working silently until the next restart.

Here's a repro with no Frigate involved. Same provider options `get_ort_providers()` builds, same IOBinding pattern as `CudaGraphRunner.run()`, and `enable_cuda_graph` is the only thing that varies:

```python
import numpy as np, onnxruntime as ort
ort.set_default_logger_severity(4)
OPTS = {"arena_extend_strategy": "kSameAsRequested",
        "use_ep_level_unified_stream": True, "device_id": 0}

def attempt(opts):
    try:
        s = ort.InferenceSession("/config/model_cache/facedet/arcface.onnx",
                                 providers=["CUDAExecutionProvider"], provider_options=[opts])
        x = np.ascontiguousarray(np.random.rand(1, 3, 112, 112).astype(np.float32))
        io = s.io_binding()
        io.bind_ortvalue_input(s.get_inputs()[0].name, ort.OrtValue.ortvalue_from_numpy(x, "cuda", 0))
        for o in s.get_outputs():
            io.bind_output(o.name, "cuda", 0)
        s.run_with_iobinding(io, ort.RunOptions()); io.copy_outputs_to_cpu()
        return True
    except Exception:
        return False

for label, o in (("ON ", {**OPTS, "enable_cuda_graph": True}), ("OFF", OPTS)):
    r = [attempt(o) for _ in range(12)]
    print(f"graph {label}: {sum(r)}/12 passed")
```

```
graph ON : 4/12 passed    [.X.XXXXXXX..]
graph OFF: 12/12 passed   [............]
```

The failure is `BFCArena: Failed to allocate memory for requested buffer of size 13871616` on `/layer4/layer4.0/conv2/Conv`, which then cascades into `CUDA failure 901 ... cudaStreamEndCapture`. That's a 13 MB allocation failing with about 88 GB of VRAM free, so it isn't memory exhaustion — ORT just can't grow the arena while a capture is in flight. @NickM-27 you were right that it's intermittent rather than deterministic, and I think that's why it's been hard to pin down.

The part I think matters most is what happens after that one failure. It lands in the `build_model` daemon thread, and `ArcFaceRecognizer.build()` only clears `model_builder_queue` on a successful `queue.get()`. So the dead thread leaves the queue permanently non-empty, `mean_embs` never populates, `classify()` returns `None` on every call from then on, and `process_frame` returns before it reaches `write_face_attempt()`.

What you see as a user is one traceback at startup and then no errors at all, no attempts written, and an empty Train tab on a fully trained library. Nothing anywhere says face recognition is off. `Finished building ArcFace model` appeared 0 times in my last 6 days of logs, while the `build_model` traceback showed up at every one of the 3 embeddings-process starts in that window, roughly 60 seconds after each start. Mine was quietly dead for nearly 6 days before I worked out why. #22728 ran into the same dead end from the other direction (empty library rather than crashed build thread) before the template bot auto-closed it.

Adding just `EnrichmentModelTypeEnum.arcface.value` to the exclusion list, bind-mounted over the file, then restarting: `Finished building ArcFace model` logged for the first time ever on this machine, 32 attempts written in the following 12 minutes with recognitions between 0.86 and 1.00, sub-labels arriving in Home Assistant, and no CUDA 901 since. Object detection still uses graph capture and is unaffected.

Two corrections to the patch posted earlier in this thread, in case anyone copies it. The `facenet` line is a no-op, because FaceNet runs through TFLite and never reaches `get_optimized_runner`, so only the `arcface` line actually does anything. And given the four other enrichment models are already excluded, this looks less like a special case for odd hardware and more like one that just got missed.

So, what I'd ask for:

1. Exclude `arcface` from CUDA graph capture, or expose `enable_cuda_graph` as a config option if you'd rather keep it available where it works fine.
2. Reset `model_builder_queue` when the build thread dies, so a transient failure retries instead of wedging permanently. That seems worth doing whatever happens with the CUDA side.
3. Unrelated, but I hit it while testing: `__detect_face` does `potential_face[0:4].astype(np.uint16)` on coordinates that can be negative. A raw `y = -7.5` wraps to `65529`, so the `max(raw[1], 0)` right after can't help and the crop ends up empty. `process_frame` survives this because it clamps and has a `face_frame.size == 0` guard, but `handle_request` has neither, so `POST /api/faces/recognize` 500s inside `cv2.Laplacian` for 4 of my 6 library faces.
4. Very minor: the `min_area` debug line logs `{face}`, which is always `None` on the manual detection path. Should be `area(face_box)`. It's confusing if you're trying to debug `min_area`.

Also worth flagging that #22524 was closed after the reporter found #22589 fixed it for them. That doesn't hold generally — #22589 is in my build and it still fails.

One thing I can't answer is why the capture fails to grow the arena on this hardware roughly two thirds of the time, or what differs between the runs that pass and the ones that don't. That feels like ORT or CUDA rather than Frigate. Happy to run more tests or put a PR together if it helps.

Environment: Frigate `0.18.0-d02a115`, `-tensorrt` image, Docker Compose on Debian. NVIDIA RTX PRO 6000 Blackwell Workstation Edition, driver 580.95.05, 96 GB. onnxruntime 1.24.4. face_recognition large, semantic_search large, LPR small and bird classification all enabled.

**Comment by NickM-27** [comment]
This has been fixed in 0.18 rc2 via https://github.com/blakeblackshear/frigate/pull/24192
