### DISCUSSION TITLE
ffmpeg issue using Nvidia

### DISCUSSION THREAD

**Discussion by svesnav** [blakeblackshear/frigate#23152] [Hardware Acceleration Support] [answered]
### Describe the problem you are having

I'm trying to configure Frigate NVR on my home server, Nvidia Driver version: 580.142. But I get an ffmpeg error, no errors are shown when using Intel iGPU

### Version

0.17.1-416a9b7

### Frigate config file

```yaml
mqtt:
  enabled: false


go2rtc:
  streams:
    front_door_cam: 
      - rtsp://user:pass@192.168.1.191:554/stream1
      - "ffmpeg:front_door_cam#audio=aac"
      - tapo://pass@192.168.1.191

  webrtc:
    candidates:
      - 192.168.1.249:8555
      - 127.0.0.1:8555


cameras:         # No cameras defined, UI wizard should be used
  front_door:
    enabled: true
    friendly_name: Front Door
    ffmpeg:
      hwaccel_args: preset-nvidia
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_cam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio

    onvif:
      host: 192.168.1.191
      port: 2020
      user: admin_camera
      password: admin_camera

    live:
      streams:
        Stream 1: front_door_cam
version: 0.17-0

record:
  enabled: True
  export:
    timelapse_args: "-vf setpts=PTS/60 -r 25"
```

### docker-compose file or Docker CLI command

```yaml
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "256mb"

    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/frigate_storage:/media/frigate
      - type: tmpfs # 1GB In-memory filesystem for recording segment storage
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "pass"
```

### Relevant Frigate log output

```shell
2026-05-10 15:04:48.269937131  [INFO] Preparing Frigate...
2026-05-10 15:04:48.570167517  [INFO] Starting Frigate...
2026-05-10 15:04:51.834329051  [2026-05-10 15:04:51] frigate.util.config            INFO    : Checking if frigate config needs migration...
2026-05-10 15:04:51.840499682  [2026-05-10 15:04:51] frigate.util.config            INFO    : frigate config does not need migration...
2026-05-10 15:04:52.591118761  [2026-05-10 15:04:52] frigate.util.services          INFO    : Automatically detected nvidia hwaccel for video decoding
2026-05-10 15:04:54.040069487  [2026-05-10 15:04:54] frigate.app                    INFO    : Starting Frigate (0.17.1-416a9b7)
2026-05-10 15:04:54.054266886  [2026-05-10 15:04:54] peewee_migrate.logs            INFO    : Starting migrations
2026-05-10 15:04:54.055079088  [2026-05-10 15:04:54] peewee_migrate.logs            INFO    : There is nothing to migrate
2026-05-10 15:04:54.071465641  [2026-05-10 15:04:54] frigate.app                    INFO    : Recording process started: 766
2026-05-10 15:04:54.082444304  [2026-05-10 15:04:54] frigate.app                    INFO    : Review process started: 779
2026-05-10 15:04:54.084469438  [2026-05-10 15:04:54] frigate.app                    INFO    : go2rtc process pid: 161
2026-05-10 15:04:54.308581368  [2026-05-10 15:04:54] frigate.app                    INFO    : Embedding process started: 789
2026-05-10 15:04:54.326401898  INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2026-05-10 15:04:54.327722067  [2026-05-10 15:04:54] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2026-05-10 15:04:54.345637884  [2026-05-10 15:04:54] frigate.app                    INFO    : Output process started: 843
2026-05-10 15:04:54.373676649  [2026-05-10 15:04:54] frigate.camera.maintainer      INFO    : Camera processor started for front_door: 894
2026-05-10 15:04:54.393816859  [2026-05-10 15:04:54] frigate.camera.maintainer      INFO    : Capture process started for front_door: 949
2026-05-10 15:04:54.527790350  [2026-05-10 15:04:54] frigate.api.fastapi_app        INFO    : Starting FastAPI app
2026-05-10 15:04:54.662698193  [2026-05-10 15:04:54] frigate.api.fastapi_app        INFO    : FastAPI started
2026-05-10 15:04:56.684989664  [2026-05-10 15:04:56] frigate.video                  ERROR   : front_door: Unable to read frames from ffmpeg process.
2026-05-10 15:04:56.685233884  [2026-05-10 15:04:56] frigate.video                  ERROR   : front_door: ffmpeg process is not running. exiting capture thread...
2026-05-10 15:05:14.397921075  [2026-05-10 15:05:14] watchdog.front_door            ERROR   : Ffmpeg process crashed unexpectedly for front_door.
2026-05-10 15:05:14.398206910  [2026-05-10 15:05:14] watchdog.front_door            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2026-05-10 15:05:14.398377537  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [h264 @ 0x558426e7fdc0] SEI type 764 size 50 truncated at 48
2026-05-10 15:05:14.398521138  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   :     Last message repeated 2 times
2026-05-10 15:05:14.398671050  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [aac @ 0x558426ea9f00] Too many bits 8832.000000 > 6144 per frame requested, clamping to max
2026-05-10 15:05:14.398817860  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [segment @ 0x558426ead380] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2026-05-10 15:05:14.398997688  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.399145911  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 522, current: 522; changing to 523. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.399316657  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 1536, current: 1536; changing to 1537. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.399559579  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 2565, current: 2565; changing to 2566. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.399784776  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 3594, current: 3594; changing to 3595. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.399996759  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [h264 @ 0x5584285d8d00] SEI type 764 size 50 truncated at 48
2026-05-10 15:05:14.400229624  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 4608, current: 4608; changing to 4609. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.400443296  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [h264 @ 0x5584285d8d00] SEI type 764 size 50 truncated at 48
2026-05-10 15:05:14.400658581  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [Parsed_scale_cuda_1 @ 0x7f7eb4003340] cu->cuModuleLoadData(cu_module, buf) failed -> CUDA_ERROR_JIT_COMPILER_NOT_FOUND: PTX JIT compiler library not found
2026-05-10 15:05:14.400874718  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [Parsed_scale_cuda_1 @ 0x7f7eb4003340] Failed to configure output pad on Parsed_scale_cuda_1
2026-05-10 15:05:14.401116267  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vf#1:0 @ 0x558426f3c680] Error reinitializing filters!
2026-05-10 15:05:14.401307083  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vf#1:0 @ 0x558426f3c680] Task finished with error code: -542398533 (Generic error in an external library)
2026-05-10 15:05:14.401512369  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vf#1:0 @ 0x558426f3c680] Terminating thread with return code -542398533 (Generic error in an external library)
2026-05-10 15:05:14.401730831  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#1:0/rawvideo @ 0x558426ea5500] Could not open encoder before EOF
2026-05-10 15:05:14.401895936  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#1:0/rawvideo @ 0x558426ea5500] Task finished with error code: -22 (Invalid argument)
2026-05-10 15:05:14.402064262  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#1:0/rawvideo @ 0x558426ea5500] Terminating thread with return code -22 (Invalid argument)
2026-05-10 15:05:14.402231084  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 5637, current: 5637; changing to 5638. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.402410378  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 6666, current: 6666; changing to 6667. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.402551170  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 7680, current: 7680; changing to 7681. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.402690438  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 8709, current: 8709; changing to 8710. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.402843246  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 9738, current: 9738; changing to 9739. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.402991560  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 11781, current: 11781; changing to 11782. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.403140696  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 12810, current: 12810; changing to 12811. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.403258059  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 13824, current: 13824; changing to 13825. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.403379789  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 15882, current: 15882; changing to 15883. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.403640552  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 16896, current: 16896; changing to 16897. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.403839970  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 18954, current: 18954; changing to 18955. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.403979226  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 19968, current: 19968; changing to 19969. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.404092784  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 22026, current: 22026; changing to 22027. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.404184967  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 23040, current: 23040; changing to 23041. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.404275787  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 24069, current: 24069; changing to 24070. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.404363249  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 25098, current: 25098; changing to 25099. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.404453803  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 26112, current: 26112; changing to 26113. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.404538776  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [vost#0:0/copy @ 0x558426e9bc00] Non-monotonic DTS; previous: 27141, current: 27141; changing to 27142. This may result in incorrect timestamps in the output file.
2026-05-10 15:05:14.404625878  [2026-05-10 15:05:14] ffmpeg.front_door.detect       ERROR   : [out#1/rawvideo @ 0x558426eab8c0] Nothing was written into output file, because at least one of its streams received no packets.
2026-05-10 15:05:14.404716901  [2026-05-10 15:05:14] watchdog.front_door            INFO    : Restarting ffmpeg...
2026-05-10 15:05:16.784231086  [2026-05-10 15:05:16] frigate.video                  ERROR   : front_door: Unable to read frames from ffmpeg process.
2026-05-10 15:05:16.784476107  [2026-05-10 15:05:16] frigate.video                  ERROR   : front_door: ffmpeg process is not running. exiting capture thread...
```

### Relevant go2rtc log output

```shell
2026-05-10 15:04:48.512418112  [INFO] Preparing new go2rtc config...
2026-05-10 15:04:48.828454872  [INFO] Starting go2rtc...
2026-05-10 15:04:49.139050727  15:04:49.138 INF go2rtc platform=linux/amd64 revision=df95ce3 version=1.9.10
2026-05-10 15:04:49.139054823  15:04:49.139 INF config path=/config/go2rtc_homekit.yml
2026-05-10 15:04:49.139454033  15:04:49.139 INF [rtsp] listen addr=:8554
2026-05-10 15:04:49.139456400  15:04:49.139 INF [api] listen addr=:1984
2026-05-10 15:04:49.139727619  15:04:49.139 INF [webrtc] listen addr=:8555
2026-05-10 15:04:58.211346744  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
ffprobe version 7.1.1-alt3 Copyright (c) 2007-2025 the FFmpeg developers
  built with gcc 13 (GCC)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/share/man --docdir=/usr/share/doc/ffmpeg-7.1.1 --disable-rpath --enable-v4l2-request --enable-amf --enable-gpl --enable-version3 --enable-pthreads --enable-shared --disable-static --enable-mmx --disable-nonfree --enable-ffplay --enable-ffprobe --enable-avfilter --disable-avisynth --enable-bzlib --enable-chromaprint --enable-frei0r --enable-gnutls --disable-ladspa --enable-libaom --disable-libaribb24 --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --disable-libcelt --enable-libcodec2 --enable-libdav1d --disable-libdavs2 --enable-libdc1394 --enable-libdrm --disable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --disable-libglslang --enable-libgme --enable-libgsm --disable-libilbc --enable-libjack --disable-libklvanc --disable-libkvazaar --disable-liblensfun --disable-libmfx --enable-libvpl --disable-libmodplug --enable-libmp3lame --enable-librabbitmq --disable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --disable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librsvg --disable-librtmp --enable-librubberband --disable-libshine --enable-libsmbclient --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --disable-libtesseract --enable-libtheora --enable-libtwolame --enable-libv4l2 --enable-libvidstab --disable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --disable-omx --enable-openal --enable-opencl --enable-opengl --disable-pocketsphinx --enable-sdl2 --enable-v4l2_m2m --enable-vaapi --disable-vapoursynth --enable-vdpau --enable-vulkan --enable-zlib --enable-cuvid --enable-hardcoded-tables --enable-runtime-cpudetect --enable-debug --disable-stripping --enable-pic --extra-cflags='-pipe -frecord-gcc-switches -Wall -g -flto=auto -fPIC -DPIC' --enable-lto --extra-version=alt3
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
[h264 @ 0x5623c2705b00] SEI type 764 size 50 truncated at 48
    Last message repeated 3 times
Input #0, rtsp, from 'rtsp://user:pass@192.168.1.191:554/stream1':
  Metadata:
    title           : Session streamed by "TP-Link RTSP Server"
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1440, 30 fps, 30 tbr, 90k tbn
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
```

### Install method

Docker Compose

### Object Detector

TensorRT

### Network connection

Wireless

### Camera make and model

TP Link Tapo TC72

### Screenshots of the Frigate UI's System metrics pages

<img width="2471" height="1199" alt="image" src="https://github.com/user-attachments/assets/2d1031d1-422d-421b-a25b-87e3e48ffab1" />

### Any other information that may be helpful

GPUs:
Nvidia Tesla V100 16GB
Geforce GTX 1080 8GB

Linux 6.12.85-6.12-alt1

Driver Version: 580.142   
CUDA Version: 13.0

**Comment by inkeep-ai-assistant** [comment]
The error `CUDA_ERROR_JIT_COMPILER_NOT_FOUND: PTX JIT compiler library not found` indicates that the CUDA JIT compiler libraries are not available inside the container. This is typically caused by missing CUDA toolkit components on the host or improper GPU passthrough configuration.

For Nvidia GPU hardware acceleration with Frigate, you need to:

**1. Install the NVIDIA Container Toolkit**

The NVIDIA Container Toolkit must be installed on your host system to allow Docker containers to access the GPU. [(1)](https://docs.frigate.video/configuration/hardware_acceleration_video)

**2. Use the correct Docker Compose configuration**

Your docker-compose configuration looks correct, but ensure you're using the proper GPU passthrough format: [(1)](https://docs.frigate.video/configuration/hardware_acceleration_video)

```yaml
services:
  frigate:
    ...
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              count: 1
              capabilities: [gpu]
```
[(1)](https://docs.frigate.video/configuration/hardware_acceleration_video)

**3. Use the preset-nvidia hwaccel argument**

Using `preset-nvidia` is correct - ffmpeg will automatically select the necessary profile for the incoming video: [(1)](https://docs.frigate.video/configuration/hardware_acceleration_video)

```yaml
ffmpeg:
  hwaccel_args: preset-nvidia
```
[(1)](https://docs.frigate.video/configuration/hardware_acceleration_video)

**4. Verify GPU access inside the container**

Run `nvidia-smi` on the host to verify the GPU is accessible. Note that `nvidia-smi` will not show ffmpeg processes when run inside the container due to Docker limitations. [(1)](https://docs.frigate.video/configuration/hardware_acceleration_video)

**5. Check driver compatibility**

While older GPUs may work, you must use a driver version that will work with FFmpeg. Older driver versions may be missing symbols and fail to work. NVIDIA provides a matrix of supported GPUs and features at their developer site. [(1)](https://docs.frigate.video/configuration/hardware_acceleration_video)

The specific error about PTX JIT compiler suggests the CUDA runtime libraries inside the container cannot find the necessary compilation tools. This may indicate a mismatch between your host driver version (580.142) and what the Frigate container expects, or incomplete CUDA library passthrough.

You may want to verify that your driver version is compatible with the FFmpeg build included in the Frigate container by checking the [driver release documentation](https://download.nvidia.com/XFree86/Linux-x86_64/525.85.05/README/supportedchips.html). [(1)](https://docs.frigate.video/configuration/hardware_acceleration_video)

📚 **Sources:**
1. [Video Decoding](https://docs.frigate.video/configuration/hardware_acceleration_video)

---

Have another question? Just tag [@inkeep](https://inkeep.com).

**Reply by svesnav** [reply]
I have NVIDIA Container Toolkit

nvidia-ctk -v installed.
NVIDIA Container Toolkit CLI version 1.17.8

<img width="737" height="404" alt="image" src="https://github.com/user-attachments/assets/5398f0c9-a0db-4b11-8d97-b9e872d32d5d" />

**Reply by NickM-27** [reply]
this will likely come from something in the host installation. Could be some missing extensions / libraries, or something needs to be added to LD_LIBRARY in the docker container. 

You can try running `libnvidia-ptxjitcompiler.so` to see if it is on the host or in the container.

**Reply by svesnav** [reply]
In Docker CLI:

`docker run --rm --runtime=nvidia   -e NVIDIA_VISIBLE_DEVICES=all   -e NVIDIA_DRIVER_CAPABILITIES=all   ubuntu:24.04   bash -c "find /usr -name '*ptxjit*' 2>/dev/null"`

`/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.580.142`
`/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1`

On host :

`find /usr -name '*ptxjit*' 2>/dev/null`

`/usr/lib64/libnvidia-ptxjitcompiler.so.580.142`
`/usr/lib64/libnvidia-ptxjitcompiler.so.1`

In Frigate Container:

`docker exec -it frigate  bash -c "find /usr -name '*ptxjit*' 2>/dev/null"`

Nothing print

<img width="1335" height="151" alt="image" src="https://github.com/user-attachments/assets/a75582f7-2e3b-4a39-9d0a-61d6dd379bcd" />

**Reply by NickM-27** [reply]
Seems for some reason docker compose is not mounting the toolkit correctly.

**Reply by svesnav** [reply]
Is there a way to fix this somehow, I couldn't find anything useful? Should I use manual mounting?

**Reply by NickM-27** [reply]
You can try manual mounting, I am unsure where the issue would be other than that it is something with the host configuration, as the nvidia container toolkit and docker are what are responsible for mounting the necessary libraries

**Reply by svesnav** [reply, marked as answer]
I tried manual mounting

`- /usr/lib64/libnvidia-ptxjitcompiler.so.580.142:/usr/lib64/libnvidia-ptxjitcompiler.so.580.142:ro`
`- /usr/lib64/libnvidia-ptxjitcompiler.so.1:/usr/lib64/libnvidia-ptxjitcompiler.so.1:ro`

And this solved the issue. Thank you for your help!
